version: 2
jobs:
    build_docs:
      docker:
        - image: cimg/python:3.9.9
        # entrypoint: [/bin/bash, -l, -c]
      steps:
        - checkout
        - run:
            name: Set BASH_ENV
            command: |
              echo "set -e" >> $BASH_ENV
              echo "export DISPLAY=:99" >> $BASH_ENV
              echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV
              echo "BASH_ENV:"
              cat $BASH_ENV

        - run:
            name: Merge with upstream
            command: |
              echo $(git log -1 --pretty=%B) | tee gitlog.txt
              echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
              if [[ $(cat merge.txt) != "" ]]; then
                echo "Merging $(cat merge.txt)";
                git remote add upstream git://github.com/QB3/sparse-ho.git;
                git pull --ff-only upstream "refs/pull/$(cat merge.txt)/merge";
                git fetch upstream master;
              fi

        # If all keys are in the same command only one is restored
        # thx @mathurinm
        # - restore_cache:
        #     keys:
        #       - data-cache-0

        # - restore_cache:
        #     keys:
        #       - pip-cache

        # - restore_cache:
        #     keys:
        #       - sparse_ho_data

        # - run:
        #     name: Spin up Xvfb
        #     command: |
        #       sudo apt update
        #       sudo apt install xvfb
        #       /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;

        - run:
            name: Setup Miniconda
            command: |
              cd $HOME
              wget "https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh" -O miniconda.sh
              chmod +x ./miniconda.sh
              bash miniconda.sh -bu
              echo "done"
              export PATH="$HOME/miniconda3/bin:$PATH"
              echo $PATH

        - run:
            name: Get Python running
            command: |
              export PATH="$HOME/miniconda3/bin:$PATH"
              conda create -y --name=mne --channel=conda-forge mne
              conda activate mne
              python -m pip install -U pip
              python -m pip install -U -r requirements.txt
              python -m pip install -U-r doc/doc-requirements.txt
              python -m pip install --user --upgrade -e .

        - save_cache:
            key: pip-cache
            paths:
              - ~/.cache/pip

        # Look at what we have and fail early if there is some library conflict
        - run:
            name: Check installation
            command: |
               export PATH="$HOME/miniconda3/bin:$PATH"
               which python
               python -c "import sparse_ho"

        # Build docs
        - run:
            name: make html
            command: |
              export PATH="$HOME/miniconda3/bin:$PATH"
              cd doc;
              make clean;
              make SPHINXOPTS=-v html;


        - save_cache:
            key: sparse_ho_data
            paths:
              - $HOME/sparse_ho_data

        # Deploy docs
        - run:
            name: deploy
            command: |
              if [[ ${CIRCLE_BRANCH} == "master" ]]; then
                set -e
                mkdir -p ~/.ssh
                echo -e "Host *\nStrictHostKeyChecking no" > ~/.ssh/config
                chmod og= ~/.ssh/config
                cd doc;
                pip install ghp-import;
                make install
              fi

        # Save the outputs
        - store_artifacts:
            path: doc/_build/html/
            destination: dev
        - persist_to_workspace:
            root: doc/_build
            paths:
              - html


workflows:
  version: 2

  default:
    jobs:
      - build_docs
